#!/usr/bin/env bash
#
# run_indexers.sh — spin up three `massa-indexer` Docker containers that
# peer with each other and share a local Massa node.
#
# Goals (matches spec.md §10.1 and §8.5):
#   * Three fully independent indexers, each with its OWN RocksDB path and
#     its OWN REST / peer gRPC ports. No collisions.
#   * All three point at the SAME local `massa-node` (run_node.sh) on
#     127.0.0.1:33037.
#   * Each indexer's peer gRPC is reachable from the other two so the
#     backfill worker can close any gaps.
#
# We use `--network host` to keep the reach-the-node and reach-the-peers
# wiring trivial on Linux. Each container therefore needs a unique REST
# port and a unique peer port. We pick contiguous ranges so it's obvious
# at a glance which container owns which:
#
#     indexer-1: REST :8081  peer :9444
#     indexer-2: REST :8082  peer :9445
#     indexer-3: REST :8083  peer :9446
#
# Data:
#   * Container `indexer-N` reads a generated config at
#     `./data/indexers/indexer-N/indexer.toml` (mounted read-only) and
#     persists RocksDB at `./data/indexers/indexer-N/rocksdb/`.
#   * Each container also gets a dedicated Docker volume name
#     (`massa-indexer-N`) for its `/data` to keep rocksdb sstables off the
#     build host's filesystem if the operator prefers; by default we bind
#     to the host path so `ls` Just Works.
#
# Usage:
#     ./run_indexers.sh build       # build the image once
#     ./run_indexers.sh up          # (re)create and start all 3
#     ./run_indexers.sh down        # stop and remove all 3
#     ./run_indexers.sh status      # `docker ps` filtered
#     ./run_indexers.sh logs N      # tail container N's logs
#
# Environment overrides:
#     INDEXER_IMAGE   — image tag (default: massa-indexer:local)
#     INDEXER_NETWORK — network id stamped into each config
#                       (default: mainnet; use buildnet as needed)
#     NODE_GRPC_URL   — gRPC URL reached from *inside* the container
#                       (default: http://127.0.0.1:33037, which works
#                        when --network=host)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

: "${INDEXER_IMAGE:=massa-indexer:local}"
: "${INDEXER_NETWORK:=mainnet}"
: "${NODE_GRPC_URL:=http://127.0.0.1:33037}"

DATA_ROOT="${SCRIPT_DIR}/data/indexers"

# One source of truth for the port layout.
# Format: "name rest_port peer_port"
INDEXERS=(
  "indexer-1 8081 9444"
  "indexer-2 8082 9445"
  "indexer-3 8083 9446"
)

usage() {
  sed -n '3,45p' "$0"
  exit 64
}

cmd_build() {
  echo "[run_indexers] building image ${INDEXER_IMAGE}"
  # Workspace root is the build context so both `massa-proto/` and
  # `massa-indexer/` are reachable; build.rs requires them as siblings.
  docker build -f massa-indexer/Dockerfile -t "${INDEXER_IMAGE}" .
}

# Generate the per-indexer `indexer.toml` into its host-side data dir.
render_config() {
  local idx_name="$1"
  local rest_port="$2"
  local peer_port="$3"

  local cfg_dir="${DATA_ROOT}/${idx_name}"
  mkdir -p "${cfg_dir}/rocksdb"

  # Other peers (name -> url) in the cluster.
  local peers_block=""
  for row in "${INDEXERS[@]}"; do
    # shellcheck disable=SC2206
    local fields=($row)
    local other_name="${fields[0]}"
    local other_peer="${fields[2]}"
    [[ "${other_name}" == "${idx_name}" ]] && continue
    peers_block+="${other_name} = { url = \"http://127.0.0.1:${other_peer}\" }"$'\n'
  done

  cat > "${cfg_dir}/indexer.toml" <<TOML
# Auto-generated by run_indexers.sh for ${idx_name}. Edit run_indexers.sh, not this.

[general]
network = "${INDEXER_NETWORK}"

[node]
grpc_url = "${NODE_GRPC_URL}"
connect_timeout_ms = 5000
keepalive_ms = 15000

[db]
path = "/data/rocksdb"
compression = "lz4"
write_buffer_size_mb = 64

[rest]
bind = "0.0.0.0:${rest_port}"
cors = ["*"]
sse_ring_buffer_size = 10000
sse_heartbeat_secs = 20
default_page_size = 50
max_page_size = 500

[peer]
enabled = true
bind = "0.0.0.0:${peer_port}"
peer_id = "${idx_name}"
scan_interval_ms = 5000
batch_size = 64
max_rpcs_per_pass = 32

[peer.peers]
${peers_block}
TOML
}

cmd_up() {
  if ! docker image inspect "${INDEXER_IMAGE}" >/dev/null 2>&1; then
    echo "[run_indexers] image ${INDEXER_IMAGE} not found — building first."
    cmd_build
  fi

  for row in "${INDEXERS[@]}"; do
    # shellcheck disable=SC2206
    local fields=($row)
    local name="${fields[0]}" rest_port="${fields[1]}" peer_port="${fields[2]}"

    render_config "${name}" "${rest_port}" "${peer_port}"

    # Make sure a previous attempt isn't in the way.
    docker rm -f "${name}" >/dev/null 2>&1 || true

    echo "[run_indexers] starting ${name} (REST :${rest_port}, peer :${peer_port})"
    docker run -d \
      --name "${name}" \
      --restart unless-stopped \
      --network host \
      -v "${DATA_ROOT}/${name}/indexer.toml:/etc/massa-indexer/indexer.toml:ro" \
      -v "${DATA_ROOT}/${name}/rocksdb:/data/rocksdb" \
      -e RUST_LOG="info,massa_indexer=info" \
      "${INDEXER_IMAGE}" \
      >/dev/null
  done

  echo "[run_indexers] all three indexers launched. Try:"
  for row in "${INDEXERS[@]}"; do
    # shellcheck disable=SC2206
    local fields=($row)
    echo "    curl -s http://127.0.0.1:${fields[1]}/v1/status | jq .meta"
  done
}

cmd_down() {
  for row in "${INDEXERS[@]}"; do
    # shellcheck disable=SC2206
    local fields=($row)
    docker rm -f "${fields[0]}" >/dev/null 2>&1 || true
    echo "[run_indexers] removed ${fields[0]}"
  done
}

cmd_status() {
  docker ps --filter 'name=^indexer-[1-3]$' \
    --format 'table {{.Names}}\t{{.Status}}\t{{.Image}}'
}

cmd_logs() {
  local which="${1:-1}"
  local target="indexer-${which}"
  exec docker logs -f --tail=200 "${target}"
}

cmd="${1:-}"
shift || true
case "${cmd}" in
  build)  cmd_build ;;
  up)     cmd_up ;;
  down)   cmd_down ;;
  status) cmd_status ;;
  logs)   cmd_logs "$@" ;;
  *)      usage ;;
esac
