#!/bin/sh
# Rewrite /usr/share/nginx/html/config.js from environment variables so an
# operator can override indexer endpoints without rebuilding the image.
#
# Recognized env vars:
#   MASSA_EXPLORER_DEFAULT_NETWORK     -> "mainnet" or "buildnet"
#   MASSA_EXPLORER_MAINNET_ENDPOINTS   -> comma-separated list of URLs
#   MASSA_EXPLORER_BUILDNET_ENDPOINTS  -> comma-separated list of URLs
#
# If none are set, the bundled defaults from src/lib/config.ts are used.

set -eu

target="/usr/share/nginx/html/config.js"

# Convert a comma-separated list into a JSON array literal. Empty values
# collapse to `null` so runtimeCfg() falls back to bundled defaults.
list_to_json() {
    in="${1:-}"
    if [ -z "$in" ]; then
        printf 'null'
        return
    fi
    # shellcheck disable=SC2086
    printf '%s' "$in" | awk -v RS=',' 'BEGIN { printf "[" }
        {
            gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "");
            if ($0 == "") next;
            if (n++ > 0) printf ", ";
            gsub(/\\/, "\\\\");
            gsub(/"/, "\\\"");
            printf "\"%s\"", $0;
        }
        END { printf "]" }'
}

default_net="${MASSA_EXPLORER_DEFAULT_NETWORK:-}"
mainnet_json=$(list_to_json "${MASSA_EXPLORER_MAINNET_ENDPOINTS:-}")
buildnet_json=$(list_to_json "${MASSA_EXPLORER_BUILDNET_ENDPOINTS:-}")

case "$default_net" in
    mainnet|buildnet) default_field="\"defaultNetwork\": \"$default_net\", " ;;
    *)                default_field="" ;;
esac

endpoints_field=""
if [ "$mainnet_json" != "null" ] || [ "$buildnet_json" != "null" ]; then
    endpoints_field="\"endpoints\": { \"mainnet\": $mainnet_json, \"buildnet\": $buildnet_json }"
fi

cat > "$target" <<EOF
// Generated by massa-explorer/docker-entrypoint.sh at container start.
window.__MASSA_EXPLORER_CONFIG__ = { ${default_field}${endpoints_field} };
EOF

echo "massa-explorer: wrote runtime config to $target"
